### ISSUE TITLE
[ModemE] Error! Wrong firmware version - please retry

### ISSUE THREAD

**Issue by zafersn** [Lora-net/SWTL001#4]
When I try to update chip with `lr1121_modem_05020001` or ` lr1121_modem_2.0.0`. I am getting an error:

```
LR11XX updater tool v2.5.1
198 WEST_TOPDIR/wsc_hw2/SWTL001/application/src/main.c
Update LR1121 to modem firmware 0x5020001
Resetting the chip...
Chip in bootloader mode:
 - Chip type               = 0xDF (0xDF for production)
 - Chip hardware version   = 0x22 (0x22 for V2C)
 - Chip bootloader version = 0x2100 
154 WEST_TOPDIR/wsc_hw2/SWTL001/application/src/lr11xx_firmware_update.c
PIN is     0x915BA277
ChipEUI is 0x0016C001F03651D7
JoinEUI is 0x0016C001FFFE0001
Start flash erase...
> Flash erase done!
Start flashing firmware...
247 WEST_TOPDIR/zephyr/drivers/lora_lbm/lr11xx/lr11xx_board.c 
*** Booting Zephyr OS build v3.7.0-rc3-173-g7c2441ec59fe ***
> Flashing done!
Rebooting...
> Reboot done!
Chip in LoRa Basics Modem-E mode:
 - Chip use case version: 0x00
 - Chip modem major version: 0x00
 - Chip modem minor version: 0x00
 - Chip modem patch version: 0x00
 - Chip lbm major version: 0x00
 - Chip lbm minor version: 0x00
 - Chip lbm patch version: 0x00
Error! Wrong firmware version - please retry.
```
after modemE driver update, chip has a software restart with  `lr11xx_bootloader_reboot( radio, false );`  and then busy pins always stays at high 

but if I try to update any version of the transceiver, it is OK and successfully flashed.  So, has anybody had ideas why this happening?

```
LR11XX updater tool v2.5.1
198 WEST_TOPDIR/wsc_hw2/SWTL001/application/src/main.c
Update LR1121 to transceiver firmware 0x0101
Resetting the chip...
Chip in bootloader mode:
 - Chip type               = 0xDF (0xDF for production)
 - Chip hardware version   = 0x22 (0x22 for V2C)
 - Chip bootloader version = 0x2100 
154 WEST_TOPDIR/wsc_hw2/SWTL001/application/src/lr11xx_firmware_update.c
PIN is     0x915BA277
ChipEUI is 0x0016C001F03651D7
JoinEUI is 0x0016C001FFFE0001
Start flash erase...
> Flash erase done!
Start flashing firmware...
247 WEST_TOPDIR/zephyr/drivers/lora_lbm/lr11xx/lr11xx_board.c 
*** Booting Zephyr OS build v3.7.0-rc3-173-g7c2441ec59fe ***
> Flashing done!
Rebooting...
> Reboot done!
Chip in transceiver mode:
 - Chip type             = 0x03
 - Chip hardware version = 0x22
 - Chip firmware version = 0x0101
Expected firmware running!
Please flash another application (like EVK Demo App).
```

**Comment by zafersn** [comment]
I resolved the issue, and now the chip update works perfectly.

The problem was that I was trying to use the same driver for communications with the modemE driver after flashing the modemE driver and rebooting. However, I discovered that the modemE driver requires a different approach (essentially its own driver, which I didn't use at that time).

Here are some key differences between the modemE and transceiver versions:

**Wake-Up Process:** The LR1121 with modemE needs to be woken up before any read or write operations.
**Busy Pin Behavior**: After writing data, the modemE driver requires waiting for the busy pin to go high, which is different from the transceiver version. we don't need to check if it goes high or not for transceiver version; we just need to ensure it is low before the next process.

![image](https://github.com/user-attachments/assets/16739457-2ebc-4260-9c6d-2d0834611d0d)

**Comment by H-sw123** [comment]
> I resolved the issue, and now the chip update works perfectly.
> 
> The problem was that I was trying to use the same driver for communications with the modemE driver after flashing the modemE driver and rebooting. However, I discovered that the modemE driver requires a different approach (essentially its own driver, which I didn't use at that time).
> 
> Here are some key differences between the modemE and transceiver versions:
> 
> **Wake-Up Process:** The LR1121 with modemE needs to be woken up before any read or write operations. **Busy Pin Behavior**: After writing data, the modemE driver requires waiting for the busy pin to go high, which is different from the transceiver version. we don't need to check if it goes high or not for transceiver version; we just need to ensure it is low before the next process.
> 
> ![image](https://github.com/user-attachments/assets/16739457-2ebc-4260-9c6d-2d0834611d0d)
Hello, I have also encountered this problem. Could you please tell me how you solved it?

![Image](https://github.com/user-attachments/assets/148cee4a-a237-4f2d-9f2f-38ae0a6bab75)

**Comment by H-sw123** [comment]
The problem has been solved. When preparing to read the information of modemE, 'lr1121_modem_system_reboot(&lr1121, false)' needs to be used;  The command can be read after waiting for another two seconds. 

![Image](https://github.com/user-attachments/assets/865e0f70-3b9a-423d-ace8-0951784947fc)
